### Note: DO NOT use quantized model or quantization_bit when merging lora adapters

### model
model_name_or_path: Qwen/Qwen2.5-7B-Instruct
adapter_name_or_path: medical_qwen25_huatuo/outputs/qwen2.5-7b-instruct/lora/sft
template: qwen
finetuning_type: lora

### export
export_dir: medical_qwen25_huatuo/outputs/qwen2.5-7b-instruct/merged
export_size: 2
export_device: cpu
export_legacy_format: false
